name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Get files
      run: for i in {1..12}; do ./get_input.sh $i; done
      env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Run Tests and Generate Jacoco Report
      run: ./gradlew jacocoTestReport

    - name: Upload Jacoco Coverage Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-coverage-report
        path: code/build/reports/jacoco/test/html

    - name: Display Jacoco Coverage HTML Report Link
      run: |
        echo "Jacoco Coverage Report available at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"

    - name: Install xmllint
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils

    - name: Extract Coverage Percentage
      run: |
        COVERAGE=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@covered)" code/build/reports/jacoco/test/jacocoTestReport.xml)
        MISSED=$(xmllint --xpath "string(//report/counter[@type='INSTRUCTION']/@missed)" code/build/reports/jacoco/test/jacocoTestReport.xml)
        TOTAL=$((COVERAGE + MISSED))
        PERCENT=$((COVERAGE * 100 / TOTAL))
        echo "COVERAGE_PERCENT = $PERCENT"

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
